version: '3.5'

services:
  api:
    build: ./blog
    ports:
      - 5000:80
    depends_on:
      - db
    networks:
      - blog-network

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
    volumes:
      - blog-data:/var/lib/mysql
    networks:
      - blog-network

volumes:
  blog-data:

networks:
  blog-network:
    driver: bridge